FROM python:3.11

EXPOSE 8000
RUN mkdir -p /home/project/flask-api
WORKDIR  /home/project/flask-api
COPY ./api .
RUN pip install --upgrade pip --no-cache-dir -r requirements.txt

# Deployment
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0","app:app"]

