# run container with command: docker run -p 8001:8001 -d --name imserver imserver:latest
# build image with command: docker build -t imserver:latest .
FROM python:3.11

EXPOSE 8001
RUN mkdir -p /home/project/im
WORKDIR  /home/project/im
COPY ./im .
RUN pip install --upgrade pip --no-cache-dir -r requirements.txt

# Deployment
CMD ["gunicorn", "--worker-class", "eventlet", "-w", "1", "-b", "0.0.0.0:8001","--capture-output","--log-level", "debug","app:app"]