name: backend_deploy

# Only trigger, when the test workflow succeeded
on:
  push:
    paths:
      - 'chatbot-backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'chatbot-backend/**'
    branches:
      - main
# Test purpose
#on: [push]

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Clean remote server
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.BACKEND_HOST}}
            username: loading8425
            key: ${{secrets.GOOGLE_SSH_KEY}}
            passphrase: ${{secrets.GOOGLE_SSH_PASSPHRASE}}
            script: | # run commands in sequence

              sudo docker rm  -f $(sudo docker ps -a --format "{{.ID}} {{.Image}}" | grep -v mongo | awk '{print $1}')
              sudo docker rmi -f $(sudo docker images --format "{{.ID}} {{.Repository}}" | grep -v mongo | awk '{print $1}')
              sudo echo "y" | sudo docker system prune
              cd /home/loading8425/COMP90018-AI-ChatBot && git pull origin main
      
      - name: run docker compose
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.BACKEND_HOST}}
            username: loading8425
            key: ${{secrets.GOOGLE_SSH_KEY}}
            passphrase: ${{secrets.GOOGLE_SSH_PASSPHRASE}}
            script: | # run commands in sequence
              cd /home/loading8425/COMP90018-AI-ChatBot/chatbot-backend
              sudo docker compose up -d --build

      - name: Wait for application to start
        run: sleep 60 # Gives enough time for the application to start. Adjust the time as needed.
      
      - name: Interface test to verify deployment
        run: |
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://chat.unimelb.games/)
          if [ "$response" -ne 200 ]; then
            echo "Interface test failed with HTTP status $response"
            exit 1
          else
            echo "Interface test succeeded with HTTP status $response"
          fi


